development:
  host: localhost
  port: 5433
  adapter: postgresql
  database: textractor_technologies_development
  username: textractor_technologies_development
  password: textractor_technologies_development

test: &TEST
  host: localhost
  adapter: postgresql
  database: textractor_technologies_test
  username: textractor_technologies_test
  password: textractor_technologies_test